import type { MetricConfig, MetricKey } from "@/types";

export const DEFAULT_STATE_ID = "918a4130-3c81-11f1-b61f-d3a5d06b2124";
export const DEFAULT_METRIC: MetricKey = "water_temperature";

export const METRICS: MetricConfig[] = [
  {
    key: "water_temperature",
    label: "Water Temp",
    unit: "°C",
    icon: "waves",
    color: "#06b6d4",
    gradientFrom: "#06b6d440",
    gradientTo: "#06b6d405",
    chartType: "area",
    thresholds: { warning: 30, critical: 38 },
    decimals: 1,
  },
  {
    key: "ph",
    label: "pH Level",
    unit: "pH",
    icon: "flask-conical",
    color: "#a78bfa",
    gradientFrom: "#a78bfa40",
    gradientTo: "#a78bfa05",
    chartType: "line",
    thresholds: { warning: 8, critical: 9 },
    decimals: 2,
  },
  {
    key: "conductivity",
    label: "Conductivity",
    unit: "µS/cm",
    icon: "zap",
    color: "#facc15",
    gradientFrom: "#facc1540",
    gradientTo: "#facc1505",
    chartType: "area",
    thresholds: { warning: 2000, critical: 3000 },
    decimals: 0,
  },
  {
    key: "turbidity",
    label: "Turbidity",
    unit: "NTU",
    icon: "eye-off",
    color: "#94a3b8",
    gradientFrom: "#94a3b840",
    gradientTo: "#94a3b805",
    chartType: "line",
    thresholds: { warning: 15, critical: 30 },
    decimals: 1,
  },
  {
    key: "salinity",
    label: "Salinity",
    unit: "mg/L",
    icon: "salt",
    color: "#34d399",
    gradientFrom: "#34d39940",
    gradientTo: "#34d39905",
    chartType: "line",
    thresholds: { warning: 1500, critical: 2500 },
    decimals: 1,
  },
  {
    key: "o2",
    label: "Dissolved O₂",
    unit: "mg/L",
    icon: "wind",
    color: "#60a5fa",
    gradientFrom: "#60a5fa40",
    gradientTo: "#60a5fa05",
    chartType: "area",
    thresholds: { warning: 0.5, critical: 1.5 },
    decimals: 2,
  },
  {
    key: "chlorophil",
    label: "Chlorophyll-a",
    unit: "µg/L",
    icon: "sprout",
    color: "#10b981",
    gradientFrom: "#10b98140",
    gradientTo: "#10b98105",
    chartType: "line",
    thresholds: { warning: 20, critical: 50 },
    decimals: 1,
  },

  {
    key: "ammonia",
    label: "NH₃ (Ammonia)",
    unit: "mg/L",
    icon: "beaker",
    color: "#ef4444",
    gradientFrom: "#ef444440",
    gradientTo: "#ef444405",
    chartType: "line",
    thresholds: { warning: 0.02, critical: 0.05 },
    decimals: 3,
  },
  {
    key: "ammonium",
    label: "NH₄⁺ (Ammonium)",
    unit: "mg/L",
    icon: "beaker",
    color: "#8b5cf6",
    gradientFrom: "#8b5cf640",
    gradientTo: "#8b5cf605",
    chartType: "line",
    thresholds: { warning: 1, critical: 2 },
    decimals: 2,
  },
  {
    key: "nh4",
    label: "TAN (NH₃/NH₄⁺)",
    unit: "mg/L",
    icon: "beaker",
    color: "#fb923c",
    gradientFrom: "#fb923c40",
    gradientTo: "#fb923c05",
    chartType: "line",
    thresholds: { warning: 2, critical: 5 },
    decimals: 2,
  },
];

export const METRIC_MAP = Object.fromEntries(
  METRICS.map((m) => [m.key, m]),
) as Record<MetricKey, MetricConfig>;

export const TIME_RANGES = [
  { value: "24h", label: "24 Hours" },
  { value: "7d", label: "7 Days" },
  { value: "30d", label: "30 Days" },
  { value: "6m", label: "6 Months" },
] as const;

export const GALLERY_IMAGES = [
  {
    id: "g1",
    url: "/src/assets/gallery/WhatsApp Image 2026-05-11 at 12.22.37.jpeg",
    filename: "Dam View 1",
  },
  {
    id: "g2",
    url: "/src/assets/gallery/WhatsApp Image2 2026-05-11 at 12.22.37.jpeg",
    filename: "Dam View 2",
  },
  {
    id: "g3",
    url: "/src/assets/gallery/WhatsApp Image 32026-05-11 at 12.22.36.jpeg",
    filename: "Dam View 3",
  },
  {
    id: "g4",
    url: "/src/assets/gallery/WhatsApp Image 42026-05-11 at 12.22.36.jpeg",
    filename: "Dam View 4",
  },
  {
    id: "g5",
    url: "/src/assets/gallery/WhatsApp Image5 2026-05-11 at 12.22.36.jpeg",
    filename: "Dam View 5",
  },
  {
    id: "g6",
    url: "/src/assets/gallery/WhatsApp Image6 2026-05-11 at 12.22.33.jpeg",
    filename: "Dam View 6",
  },
  {
    id: "g7",
    url: "/src/assets/gallery/WhatsApp Image7 2026-05-11 at 12.22.32.jpeg",
    filename: "Dam View 7",
  },
];
