import type { MetricConfig, MetricKey } from '@/types'

export const DEFAULT_STATE_ID = '918a4130-3c81-11f1-b61f-d3a5d06b2124'
export const DEFAULT_METRIC: MetricKey = 'temperature'

export const METRICS: MetricConfig[] = [
  {
    key: 'temperature',
    label: 'Air Temperature',
    unit: '°C',
    icon: 'thermometer',
    color: '#f97316',
    gradientFrom: '#f9731640',
    gradientTo: '#f9731605',
    chartType: 'area',
    thresholds: { warning: 35, critical: 42 },
    decimals: 1,
  },
  {
    key: 'water_temperature',
    label: 'Water Temp',
    unit: '°C',
    icon: 'waves',
    color: '#06b6d4',
    gradientFrom: '#06b6d440',
    gradientTo: '#06b6d405',
    chartType: 'area',
    thresholds: { warning: 30, critical: 38 },
    decimals: 1,
  },
  {
    key: 'humidity',
    label: 'Humidity',
    unit: '%',
    icon: 'droplets',
    color: '#38bdf8',
    gradientFrom: '#38bdf840',
    gradientTo: '#38bdf805',
    chartType: 'area',
    thresholds: { warning: 85, critical: 95 },
    decimals: 0,
  },
  {
    key: 'ph',
    label: 'pH Level',
    unit: 'pH',
    icon: 'flask-conical',
    color: '#a78bfa',
    gradientFrom: '#a78bfa40',
    gradientTo: '#a78bfa05',
    chartType: 'line',
    thresholds: { warning: 8, critical: 9 },
    decimals: 2,
  },
  {
    key: 'conductivity',
    label: 'Conductivity',
    unit: 'µS/cm',
    icon: 'zap',
    color: '#facc15',
    gradientFrom: '#facc1540',
    gradientTo: '#facc1505',
    chartType: 'area',
    thresholds: { warning: 2000, critical: 3000 },
    decimals: 0,
  },
  {
    key: 'turbidity',
    label: 'Turbidity',
    unit: 'NTU',
    icon: 'eye-off',
    color: '#94a3b8',
    gradientFrom: '#94a3b840',
    gradientTo: '#94a3b805',
    chartType: 'line',
    thresholds: { warning: 15, critical: 30 },
    decimals: 1,
  },
  {
    key: 'salinity',
    label: 'Salinity',
    unit: 'mg/L',
    icon: 'salt',
    color: '#34d399',
    gradientFrom: '#34d39940',
    gradientTo: '#34d39905',
    chartType: 'line',
    thresholds: { warning: 1500, critical: 2500 },
    decimals: 1,
  },
  {
    key: 'o2',
    label: 'Dissolved O₂',
    unit: 'mg/L',
    icon: 'wind',
    color: '#60a5fa',
    gradientFrom: '#60a5fa40',
    gradientTo: '#60a5fa05',
    chartType: 'area',
    thresholds: { warning: 0.5, critical: 1.5 },
    decimals: 2,
  },
  {
    key: 'nh4',
    label: 'TAN (Azote ammoniacal total)',
    unit: 'mg/L',
    icon: 'beaker',
    color: '#fb923c',
    gradientFrom: '#fb923c40',
    gradientTo: '#fb923c05',
    chartType: 'line',
    thresholds: { warning: 2, critical: 5 },
    decimals: 2,
  },
  {
    key: 'volume',
    label: 'Dam Volume',
    unit: '%',
    icon: 'database',
    color: '#2dd4bf',
    gradientFrom: '#2dd4bf40',
    gradientTo: '#2dd4bf05',
    chartType: 'area',
    thresholds: { warning: 90, critical: 98 },
    decimals: 0,
  },
]

export const METRIC_MAP = Object.fromEntries(
  METRICS.map((m) => [m.key, m])
) as Record<MetricKey, MetricConfig>

export const TIME_RANGES = [
  { value: '24h', label: '24 Hours' },
  { value: '7d', label: '7 Days' },
  { value: '30d', label: '30 Days' },
  { value: '6m', label: '6 Months' },
] as const
